version: "3.9"

services:

  live:
    build:
      context: .
      dockerfile: live/Dockerfile
      target: live  # default anyways
      args:
        - STRAPI_BASE_TAG=v${MAJOR}.${MINOR}.${UPDATE}-n${NODE_VER}
    image: ${REGISTRY:-docker.io}/${DOCKER_U:-libre}/strapi-live:${TAG:-v3}

  cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
      args:
        - BASE_NODE_VERSION=${NODE_VER}
        - STRAPI_VER=${MAJOR}.${MINOR}.${UPDATE}
    image: ${REGISTRY:-docker.io}/${DOCKER_U:-libre}/strapi:v${MAJOR}.${MINOR}.${UPDATE}-n${NODE_VER}

  base:
    build:
      context: .
      dockerfile: base/Dockerfile
      target: base
      args:
        - NODE_BASE=${NODE_VER}-alpine
    image: ${REGISTRY:-docker.io}/${DOCKER_U:-libre}/strapi-base:node-${NODE_VER}

  cache:
    build:
      context: .
      dockerfile: cache/Dockerfile
      target: cache
      args:
        - NODE_BASE=${NODE_VER}-alpine
        - STRAPI_VER=${MAJOR}.${MINOR}.${UPDATE}
    image: ${REGISTRY:-docker.io}/${DOCKER_U:-libre}/strapi-cache:v${MAJOR}.${MINOR}.${UPDATE}-n${NODE_VER}
